title: Percona UBI-8 Container Images for PostgreSQL %!{PG_MAJOR_VERSION}
description: |
  This project contains UBI-8 based container images for Percona Software for PostgreSQL %!{PG_MAJOR_VERSION}.

repositories:
  - name: UBI_8
    paths:
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-8
        repository: standard
    archs: [x86_64, aarch64]
  - name: images
    paths:
      - subproject: ppg:%!{PG_MAJOR_VERSION}:containers:ubi8
        repository: UBI_8
      - subproject: ppg:%!{PG_MAJOR_VERSION}
        repository: UBI_8
      - subproject: ppg:common:deps
        repository: UBI_8
      - subproject: common:containers:ubi8
        repository: images
      - subproject: common:containers:ubi8
        repository: UBI_8
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}Fedora:EPEL:8
        repository: standard
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-8
        repository: standard
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:8
        repository: appstream
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:8
        repository: baseos
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:8
        repository: devel
    archs: [x86_64, aarch64]

publish:
  UBI_8: false

project-config: |
  %if "%_repository" == "UBI_8"
  ExpandFlags: module:container-tools-rhel8
  ExpandFlags: module:llvm-toolset-rhel8
  ExpandFlags: module:perl-5.26
  ExpandFlags: module:perl-IO-Socket-SSL-2.066
  ExpandFlags: module:perl-libwww-perl-6.34
  Prefer: selinux-policy-targeted
  %endif

  %if "%_repository" == "images"
  Type: docker
  BuildEngine: podman

  ExpandFlags: module:container-tools-rhel8
  Preinstall: skopeo

  ExpandFlags: filterbasecontainerpkgs
  Prefer: redhat-release
  Prefer: glibc-minimal-langpack
  Prefer: gpgme
  Prefer: iptables-nft
  Prefer: percona-postgresql%!{PG_MAJOR_VERSION}-libs
  Ignore: rocky-release

  Prefer: glibc-minimal-langpack

  BuildFlags: sbom:spdx
  BuildFlags: sbom:cyclonedx
  PublishFlags: withsbom
  %endif

qa:
  pipeline: docker-server-parallel-generic
  parameters:
    DOCKER_TAG: "%!{PG_MAJOR_VERSION}"
    SERVER_VERSION: "%!{PG_VERSION}"
    TESTING_BRANCH: ricardo-work
    REPOSITORY: registry.opensuse.org/${OBS_CONTAINER_REGISTRY_ROOTPRJ}/ppg/%!{PG_MAJOR_VERSION}/containers/ubi8/images
    WITH_POSTGIS:
      - true
      - false
  matrix:
    - WITH_POSTGIS