title: Percona UBI-9 Container Images for PostgreSQL 18
description: |
  This project contains UBI-9 based container images for Percona Software for PostgreSQL 18.

repositories:
  - name: RockyLinux_9
    paths:
      - subproject: common:deps:build
        repository: RockyLinux_9
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:9
        repository: standard
    archs: [x86_64, aarch64]
  - name: images
    paths:
      - subproject: ppg:18:containers:ubi9
        repository: RockyLinux_9
      - subproject: ppg:18
        repository: RockyLinux_9
      - subproject: ppg:17
        repository: RockyLinux_9
      - subproject: common:containers:ubi9
        repository: images
      - subproject: common:containers:ubi9
        repository: RockyLinux_9
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}Fedora:EPEL:9
        repository: standard
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:9
        repository: appstream
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-9
        repository: appstream
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-9
        repository: baseos
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:9
        repository: baseos
    archs: [x86_64, aarch64]

publish:
  RockyLinux_9: false

project-config: |
  %if "%_repository" == "RockyLinux_9"
  Type: spec
  Ignore: kbd-legacy < 2.4.0-11
  %endif

  %if "%_repository" == "images"
  Type: docker
  BuildEngine: podman

  ExpandFlags: filterbasecontainerpkgs
  Prefer: redhat-release
  Prefer: glibc-minimal-langpack
  Prefer: gpgme
  Prefer: iptables-nft
  Ignore: rocky-release

  Prefer: glibc-minimal-langpack

  BuildFlags: sbom:spdx
  BuildFlags: sbom:cyclonedx
  PublishFlags: withsbom
  %endif

qa:
  - pipeline: docker-server-parallel-generic
    parameters:
      DOCKER_TAG: 18
      SERVER_VERSION: 18.3
      TESTING_BRANCH: ricardo-work
      REPOSITORY: registry.opensuse.org/${OBS_CONTAINER_REGISTRY_ROOTPRJ}/ppg/18/containers/ubi9/images
      WITH_POSTGIS:
        - true
        - false
    matrix:
      - WITH_POSTGIS

  - pipeline: ppg-obs-upgrade
    parameters:
      REPOSITORY: registry.opensuse.org/${OBS_CONTAINER_REGISTRY_ROOTPRJ}/ppg/18/containers/ubi9/images
      OLD_SERVER_VERSION: 17.9
      NEW_SERVER_VERSION: 18.3
      UPGRADE_DOCKER_TAG: 18-17
      OLD_DOCKER_REPOSITORY: registry.opensuse.org/isv/percona/ppg/17/containers/ubi9/images
      TESTING_BRANCH: ricardo-work
