Format: 3.0 (quilt)
Source: percona-postgresql-%!{PG_MAJOR_VERSION}
Binary: libpq-dev,
        libpq5,
        libpq-oauth,
        libecpg6,
        libecpg-dev,
        libecpg-compat3,
        libpgtypes3,
        percona-postgresql-%!{PG_MAJOR_VERSION},
        percona-postgresql-client-%!{PG_MAJOR_VERSION},
        percona-postgresql-server-dev-%!{PG_MAJOR_VERSION},
        percona-postgresql-doc-%!{PG_MAJOR_VERSION},
        percona-postgresql-plperl-%!{PG_MAJOR_VERSION},
        percona-postgresql-plpython3-%!{PG_MAJOR_VERSION},
        percona-postgresql-pltcl-%!{PG_MAJOR_VERSION},
        percona-postgresql-%!{PG_MAJOR_VERSION}-jit
Architecture: any all
Version: 1.0
Maintainer: Percona Development Team <info@percona.com>
Build-Depends: autoconf,
               bison,
               clang [!alpha !hppa !hurd-i386 !ia64 !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !riscv64 !sh4 !sparc64 !x32],
               debhelper-compat (= 13),
               dh-exec (>= 0.13~),
               docbook-xml,
               docbook-xsl (>= 1.77),
               dpkg-dev (>= 1.16.1~),
               flex,
               gdb <!nocheck>,
               gettext,
               krb5-multidev,
               libcurl4-openssl-dev [linux-any],
               libedit-dev,
               libicu-dev,
               libio-pty-perl <!nocheck>,
               libipc-run-perl <!nocheck>,
               libkrb5-dev,
               libldap2-dev,
               liblz4-dev,
               libnuma-dev [linux-any],
               libpam0g-dev | libpam-dev,
               libperl-dev,
               libreadline-dev,
               libselinux-dev [linux-any],
               libssl-dev,
               libsystemd-dev [linux-any],
               liburing-dev [linux-any],
               libxml2-dev,
               libxml2-utils,
               libxslt1-dev,
               llvm-dev [!alpha !hppa !hurd-i386 !ia64 !kfreebsd-amd64 !kfreebsd-i386 !m68k !powerpc !riscv64 !sh4 !sparc64 !x32],
               mawk,
               openssl,
               perl (>= 5.8),
               percona-postgresql-common-dev,
               pkgconf,
               python3-dev,
               systemtap-sdt-dev,
               tcl-dev,
               tzdata <!nocheck>,
               uuid-dev,
               xsltproc,
               libzstd-dev (>= 1.4.0),
               zlib1g-dev | libz-dev
Debtransform-Release: 1
Debtransform-Files-Tar: debian.tar.gz
