title: Percona UBI-8 Base Container Images
description: |
  This project contains UBI-8 base container images used by the several Percona distributions.
publish: false
repositories:
  - name: UBI_8
    paths:
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-8
        repository: standard
    archs: [x86_64, aarch64]
  - name: images
    paths:
      - subproject: common:containers:ubi8
        repository: UBI_8
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-8
        repository: appstream
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-8
        repository: baseos
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:8
        repository: appstream
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:8
        repository: baseos
    archs: [x86_64, aarch64]

project-config: |
  %if "%_repository" == "UBI_8"
  Type: spec
  Ignore: kbd-legacy < 2.4.0-11

  ExpandFlags: module:container-tools-rhel8
  ExpandFlags: module:llvm-toolset-rhel8
  ExpandFlags: module:perl-5.26
  ExpandFlags: module:perl-IO-Socket-SSL-2.066
  ExpandFlags: module:perl-libwww-perl-6.34
  ExpandFlags: module:python39-3.9

  Prefer: selinux-policy-targeted

  %endif

  %if "%_repository" == "images"
  Type: kiwi
  Repotype: none
  Patterntype: none

  ExpandFlags: module:perl-5.26
  ExpandFlags: module:perl-IO-Socket-SSL-2.066
  ExpandFlags: module:perl-libwww-perl-6.34
  ExpandFlags: module:llvm-toolset-rhel8
  ExpandFlags: module:perl-DBD-Pg-3.7
  ExpandFlags: module:perl-DBI-1.641

  ExpandFlags: kiwi-nobasepackages
  Preinstall: filesystem glibc libgcc audit-libs bzip2-libs libacl libattr libarchive libcap libcap-ng lz4-libs libxml2 libzstd lua-libs openssl-libs popt sqlite-libs xz-libs zlib rpm-libs rpm util-linux-user umoci xz
  Ignore: obs-service-kiwi_label_helper:libxslt-tools
  Ignore: python39-kiwi:screen
  Ignore: kiwi-systemdeps-core:mtools

  Prefer: openssl-fips-provider
  Prefer: glibc-minimal-langpack
  Prefer: redhat-release
  Ignore: rocky-release
  Substitute: rocky-release redhat-release

  BuildFlags: container-compression-format:zstd
  BuildFlags: container-build-format:oci

  %endif
