#!/bin/bash

# Copyright (c) 2014, 2015, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ];
then
. /usr/share/debconf/confmodule
fi

case "$1" in
	remove | purge)
	# The extension no longer owns /usr/local/percona/telemetry/pg.
	# Leftover empty dirs from <= 1.1 are cleaned in postinst.
	;;

	upgrade | failed-upgrade | abort-install | abort-upgrade | disappear)

	;;

	*)
        echo "postrm called with unknown argument '$1'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
