title: Packages for PostgreSQL %!{PG_MAJOR_VERSION} Custom Images
description: |
  Packages for PostgreSQL %!{PG_MAJOR_VERSION} Custom Images — the server and the extensions
repositories:
  - name: UBI_9
    paths:
      - subproject: ppg:common:deps
        repository: UBI_9
      - subproject: common:deps:build
        repository: UBI_9
      - subproject: ppg:staging:%!{PG_MAJOR_VERSION}
        repository: UBI_9
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}Fedora:EPEL:9
        repository: standard
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RedHat:UBI-9
        repository: standard
      - project: ${REMOTE_OBS_ORG_INTERCONNECT}RockyLinux:9
        repository: devel
    archs: [x86_64, aarch64]

project-config: |
  %if "%_repository" == "RockyLinux_9" || "%_repository" == "UBI_9"
  ExpandFlags: module:llvm-toolset-rhel9
  # hdf-libs (EPEL split package) and hdf both provide libdf.so.0 and libmfhdf.so.0
  Prefer: hdf-libs
  %endif
